cudami:
  defaultLocale-gui: en
  server:
    address: http://localhost:9000
  
endpoints:
  hypermedia:
    enabled: true

info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @maven.compiler.source@
      target: @maven.compiler.target@
    project:
      name: '@project.name@'
      groupId: @project.groupId@
      artifactId: @project.artifactId@
      version: @project.version@

management:
  context-path: '/monitoring'
  port: 9001
  security:
    enabled: false
#    roles: SUPERUSER
# default role is "ACTUATOR"

security:
  basic:
    enabled: false
  headers:
    cache: false
    # disables pragma no-cache header

server:
  port: 9898
  server-header: "@project.name@ v@project.version@"

# upload config: see org.springframework.boot.autoconfigure.web.MultipartProperties
spring:
  http:
    multipart:
      # Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes respectively.
      file-size-threshold: 1MB
      location: /tmp
      max-file-size: 5MB
      max-request-size: 25MB
      # resolve-lazily: false
  profiles:
    active: local
  thymeleaf:
    cache: false
    mode: HTML
    # Order of the template resolver in the chain. (order 1 is the common classpath resolver)
    template-resolver-order: 2

---

management:
  security:
    enabled: true

security:
  user:
    name: admin
    password: secret

spring:
  profiles: PROD
  thymeleaf:
    cache: true
